// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mdrzznobsoijvppzibnx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1kcnp6bm9ic29panZwcHppYm54Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMDM2NzgsImV4cCI6MjA2Nzc3OTY3OH0.xvr79sLLCjx5OdbgZSO0hXpuSKnx03L9iJCatG6FhQY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});